<?php

namespace AppBundle\Repository;

/**
 * AppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppRepository extends \Doctrine\ORM\EntityRepository
{
}
