<?php

namespace AppBundle\Repository;

/**
 * PageTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
