app_frontend:
    resource: '@AppBundle/Controller/Frontend/'
    type: annotation
app_backend:
    resource: '@AppBundle/Controller/Backend/'
    type: annotation
    prefix: /admin
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"