services:
    app.handler.login_success:
        class:  AppBundle\Component\Authentication\Handler\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    app.handler.logout_success:
        class: AppBundle\Component\Authentication\Handler\LogoutSuccessHandler
        arguments:  ['@router']
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    app.service.email_notification:
        class: AppBundle\Service\EmailNotificationService
        arguments:  ['@mailer']
